export class Natural {


    constructor(
        public tipoSolicitante: String,
        public nombre: String,
        public documento: String,
        public sexo: String,
        public nacimiento: String,
        public pais: String,
        public estadoCivil: String,
        public dirResidencia: String,
        public ciudad: String,
        public telefono: String,
        public dirCorrespondencia: String,
        public ciudadOf: String,
        public celular: String,
        public tipoB: String,
        public nombreB: String,
        public documentoB: String,
        public sexoB: String,
        public nacimientoB: String,
        public paisB: String,
        public estadoCivilB: String,
        public dirResidenciaB: String,
        public ciudadB: String,
        public telefonoB: String,
        public dirCorrespondenciaB: String,
        public ciudadBof: String,
        public celularB: String,
        public profesion: String,
        public empresa: String,
        public cargo: String,
        public ingresos: String,
        public activos: String,
        public pasivos: String,
        public entidad: String,
        public tipo: String,
        public numero: String,
        public titular: String,
        public doc1: String,
        public doc2: String,
        public doc3: String,
        public doc4: String,
      //  public doc5: String,
        public aprobabo: boolean,
        public usuario?: string,
                 ) { }


}

